INSERT INTO units(name, slug)
VALUES
   ("Aegis", "aegis"),
   ("Amporilla", "amporilla"),
   ("Animus", "animus"),
   ("Antima Comet", "antima_comet"),
   ("Apollo", "apollo"),
   ("Arka Sodara", "arka_sodara"),
   ("Arms Race", "arms_race"),
   ("Asteri Cannon", "asteri_cannon"),
   ("Auric Impulse", "auric_impulse"),
   ("Auride Core", "auride_core"),
   ("Barrier", "barrier"),
   ("Blastforge", "blastforge"),
   ("Blood Pact", "blood_pact"),
   ("Blood Phage", "blood_phage"),
   ("Bloodrager", "bloodrager"),
   ("Borehole Patroller", "borehole_patroller"),
   ("Cauterizer", "cauterizer"),
   ("Centrifuge", "centrifuge"),
   ("Centurion", "centurion"),
   ("Chieftain", "chieftain"),
   ("Chrono Filter", "chrono_filter"),
   ("Cluster Bolt", "cluster_bolt"),
   ("Colossus", "colossus"),
   ("Conduit", "conduit"),
   ("Corpus", "corpus"),
   ("Cryo Ray", "cryo_ray"),
   ("Cynestra", "cynestra"),
   ("Deadeye Operative", "deadeye_operative"),
   ("Defense Grid", "defense_grid"),
   ("Doomed Drone", "doomed_drone"),
   ("Doomed Mech", "doomed_mech"),
   ("Doomed Wall", "doomed_wall"),
   ("Drake", "drake"),
   ("Drone", "drone"),
   ("Ebb Turbine", "ebb_turbine"),
   ("Electrovore", "electrovore"),
   ("Endotherm Kit", "endotherm_kit"),
   ("Energy Matrix", "energy_matrix"),
   ("Engineer", "engineer"),
   ("Feral Warden", "feral_warden"),
   ("Ferritin Sac", "ferritin_sac"),
   ("Fission Turret", "fission_turret"),
   ("Flame Animus", "flame_animus"),
   ("Forcefield", "forcefield"),
   ("Frostbite", "frostbite"),
   ("Frost Brooder", "frost_brooder"),
   ("Galvani Drone", "galvani_drone"),
   ("Gauss Cannon", "gauss_cannon"),
   ("Gauss Charge", "gauss_charge"),
   ("Gauss Fabricator", "gauss_fabricator"),
   ("Gaussite Symbiote", "gaussite_symbiote"),
   ("Grenade Mech", "grenade_mech"),
   ("Grimbotch", "grimbotch"),
   ("Hannibull", "hannibull"),
   ("Hellhound", "hellhound"),
   ("Husk", "husk"),
   ("Iceblade Golem", "iceblade_golem"),
   ("Immolite", "immolite"),
   ("Infusion Grid", "infusion_grid"),
   ("Iso Kronus", "iso_kronus"),
   ("Kinetic Driver", "kinetic_driver"),
   ("Lancetooth", "lancetooth"),
   ("Lucina Spinos", "lucina_spinos"),
   ("Mahar Rectifier", "mahar_rectifier"),
   ("Manticore", "manticore"),
   ("Militia", "militia"),
   ("Mobile Animus", "mobile_animus"),
   ("Nitrocybe", "nitrocybe"),
   ("Nivo Charge", "nivo_charge"),
   ("Odin", "odin"),
   ("Omega Splitter", "omega_splitter"),
   ("Ossified Drone", "ossified_drone"),
   ("Oxide Mixer", "oxide_mixer"),
   ("Perforator", "perforator"),
   ("Pixie", "pixie"),
   ("Plasmafier", "plasmafier"),
   ("Plexo Cell", "plexo_cell"),
   ("Polywall", "polywall"),
   ("Protoplasm", "protoplasm"),
   ("Redeemer", "redeemer"),
   ("Resophore", "resophore"),
   ("Rhino", "rhino"),
   ("Savior", "savior"),
   ("Scorchilla", "scorchilla"),
   ("Sentinel", "sentinel"),
   ("Shadowfang", "shadowfang"),
   ("Shiver Yeti", "shiver_yeti"),
   ("Shredder", "shredder"),
   ("Steelforge", "steelforge"),
   ("Steelsplitter", "steelsplitter"),
   ("Synthesizer", "synthesizer"),
   ("Tantalum Ray", "tantalum_ray"),
   ("Tarsier", "tarsier"),
   ("Tatsu Nullifier", "tatsu_nullifier"),
   ("Tesla Coil", "tesla_coil"),
   ("Thermite Core", "thermite_core"),
   ("The Wincer", "the_wincer"),
   ("Thorium Dynamo", "thorium_dynamo"),
   ("Thunderhead", "thunderhead"),
   ("Tia Thurnax", "tia_thurnax"),
   ("Trinity Drone", "trinity_drone"),
   ("Tyranno Smorcus", "tyranno_smorcus"),
   ("Urban Sentry", "urban_sentry"),
   ("Vai Mauronax", "vai_mauronax"),
   ("Valkyrion", "valkyrion"),
   ("Venge Cannon", "venge_cannon"),
   ("Vivid Drone", "vivid_drone"),
   ("Wall", "wall"),
   ("Wild Drone", "wild_drone"),
   ("Xaetron", "xaetron"),
   ("Xeno Guardian", "xeno_guardian"),
   ("Zemora Voidbringer", "zemora_voidbringer");
